### ISSUE TITLE
BadImageFormatException when trying to create a WyphonPartner

### ISSUE THREAD

**Issue by ResolumeMenno** [mrft/Wyphon#1]
When running the TestWyphonDotNet function the WyphonDotNet.dll encounters a System.BadImageFormatException when trying to create a native WyphonPartner inside the C# WyphonPartner constructor.

**Comment by mrft** [comment]
Hello,

my first assumption would be that (I had something similar, but due to
localized error messages I don't know if it was exactly the same) the dll
is compiled as Win32 or something, instead of x86 (if you're working in a
32-bit system).

In my case (I'm using SharpDevelop), I think I set Platform to x86 to
compile the dll's, then I set it back to Win32 to compile the console
application.

I hope this is of any help, otherwise don't hesitate to contact me again.

Just curious: how did you find the source code, and why are you interested?
Do you have any specific projects where you would like to use this?

Kind regards,

Frederik

2013/1/11 ResolumeMenno notifications@github.com

**Comment by ResolumeMenno** [comment]
Hello Frederik,

Thank you for your quick reply. It was a mismatched architecture like you
mentioned. I am working on a x64 system but the dlls were being compiled
for x86. This does not work well when the ShareDataTest and WyphonDotNet
projects are put on Any CPU. What i have done is change the test projects
to x86 and that resolves the issue.
My assumption is that when the test projects are put to Any CPU that they
are run at native architecture, which is a mismatch with the forced dll
architecture. But i'm not so much into C# and CLI so i could easilly be
wrong about this. Since the Wyphon dll seems to be the core module we're
fine with adapting the test app to run it, so this issue can be closed if
you want. (or should/can i do that? new to github)

My interest in this project is because we're building vj-ing software that
currently benefits from syphon on Mac. We would like to have a windows
equivalent so that we can for example support interoperability between our
software and VVVV.
For your information:
-our software: http://resolume.com/software/
-VVVV: http://vvvv.org/

We have been looking for a windows equivalent of syphon for a while and
just recently found your github repo. If we were to use this it would be in
a future version of our software package, support is not currently planned,
it's just something on our wishlist.
Wyphon on itself will not be something we can use directly since our
software is OpenGL based. We are thinking we may be able to do the surface
sharing over DirectX and then use an interoperability extension like this
onehttp://developer.download.nvidia.com/opengl/specs/WGL_NV_DX_interop.txt.
Do you have any experience for cross process surface sharing for OpenGL or
got any tips for us?

One last question, do you plan on creating a graphical sample application
which also shows the required DirectX setup? For example Syphon has a
sample server and client application where the server propagates a surface
for clients to receive. This could also help integrating Wyphon as there is
a running test server so only the client side has to be implemented.

Kind Regards,
Menno

**Comment by mrft** [comment]
Hello Menno,

As you might have seen, this repository has been online only for about a
week, which is why I was (happily) surprised to get such a quick response.

I would be really happy if my work could help open up the same
possibilities on Windows that are available on Mac.
As you can see on this thread on the vvvv forum, I only told the people
over there about what I was doing only 3 days ago:
http://vvvv.org/forum-alpha/something-like-syphon-on-windows-(currently-called-wyphon)#comment-94485

As you can see I posted some very first vvvv-only demo's here, but if it
gets a little more mature (just follow that thread on vvvv.org), I hope it
will be a breeze to create a server in vvvv, and a client if you need one.
Actually both are already in the example, but what I send in the messages
now is not ready for interoperability with other sotfwares yet (but it is
my intention to make that happen of course, I specifically don't want it to
be vvvv-only).

At this time, I have only created a few functions that allow for easy
sharing of the necessary data, and currently as you might have seen there
is no support at all for anything more than that, because I suppose that
application developers who get that information can easily create their own
textures and use them as they please using that information.

It would be nice to have another message type like ShareOpenGLTexture, but
as you can see I haven't done that yet.

I also know about that extension but I am not using NVidia hardware, so I
can't test that yet, but I think I heard a rumour about someone
implementing OpenGL support on the vvvv forums.

Can I invite you to this thread on the vvvv forum, to communicate about
this further?

 (I know about Resolume BTW, tried a few things with it once, but for what
I was doing at the time, I needed the flexibility of vvvv, a combination of
the 2 could be a strong team though)

2013/1/11 ResolumeMenno notifications@github.com

> do you plan on creating a graphical sample application
> which also shows the required DirectX setup? For example Syphon has a
> sample server and client application where the serv

**Comment by brucelane** [comment]
hello,
I am a developer for Onyx-VJ and I am definitely interested in this project!
I can't compile because of this x86 thingy, but I have to try harder...
Do you have some samples to try it out?

**Comment by mrft** [comment]
Only some vvvv stuff (but precompiled so maybe easier to get started from,
and more helping hands) for the moment, so please follow the vvvv forum
thread I posted earlier a bit, and add your ideas/questions/remarks over
there.

If we can get the discussion going on over there, we could probably take
the next steps quite soon.

2013/1/17 Bruce LANE notifications@github.com

**Comment by brucelane** [comment]
yes, sorry, I was excited ;-), you can remove this comment
